language: php
matrix:
  include:
  - php: 7.3
cache:
  directories:
  - $HOME/.composer/cache
before_script:
- composer self-update
- composer update --prefer-dist --no-interaction --no-progress
script:
- composer code-style
- composer tests-ci
after_script:
  - if [ "${TRAVIS_ALLOW_FAILURE}" = false ]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar && php coveralls.phar --verbose; fi
notifications:
  email: false