language: php
matrix:
  include:
  - php: 7.3
cache:
  directories:
  - $HOME/.composer/cache
before_script:
- composer self-update
- composer update --prefer-dist --no-interaction --no-progress
script:
- composer code-style
- composer tests-ci
notifications:
  email: false